### ISSUE TITLE
feature shape not matching with the ones extracted from LIBROSA

### ISSUE THREAD

**Issue by MRK4863** [novoic/surfboard#20]
![surfboard_issue](https://user-images.githubusercontent.com/45512569/94762708-17a48d00-03c6-11eb-8c86-e6863cca752e.jpg)

for a hop_length of 10ms, the shape of MFCC feature extracted from SURFBOARD and LIBROSA is DIFFERENT!!

I made sure the parameters in both the scenarios are the same.

Could you explain why does this happen

**Comment by rlenain** [comment]
Hi there!
Thanks for your comment! And thanks for noticing this and reporting it.

The way Surfboard works is that given a `hop_length_ms` and a `sample_rate`, we convert from number of ms to number of samples by finding the closest power of 2. This is done via the `numseconds_to_numsamples` function which you can find in `surfboard/surfboard/utils.py`. The reason we do this is that processing is more efficient in this regime.

For example, if you load a sound with 44,1kHz, and a `hop_length_ms=10` which is 0.01 seconds, we find the closest power of 2 to 44,100 * 0.01 = 441. The closest power of 2 is then 512. So the hop length is slightly larger than 10ms, which is why you are getting a slightly smaller array.

Does this make sense?
Is this behaviour undesirable to you?

**Comment by MRK4863** [comment]
Thanks for the Reply. 
Now I understood the working. It was indeed very helpful. 
I had been working on a few other libraries before and I never got a response so fast. I really appreciate your effort.
And once again, Thank you.
